### PR TITLE
TimePicker widget now saves the time instead of date by default, if y…

### LINKED ISSUE #183: [bug]: jqui - Input Time
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

 jqui - Input Time (gestylt)

image

Nach Eingabe einer Zeit wird im Datenpunkt "2023-11-20T01:10:00.000Z" dieses Format abgelegt.
(Datenpunkt ist als string mit unit hh:mm definiert)

Ist im Datenpunkt der Wert "2023-11-20T01:10:00.000Z" gespeichert, stürzt VIS-2 nach einem Reload des Fensters mit eine weissen Bildschirm ab. Setze ich den Datenpunkt manuell auf "06:45" kann ich die Seite wieder laden. 
Siehe F12-Protokoll vom Chrome-Browser

Aufgefallen ist mir dies nach der Installation von VIS-2 Version 2.6.1 (ich vermute aber, dass dies schon mit 2.5.4 vorhanden war)

Ich verwende das Widget für den Adapter HeatingControl über Pittini´s Simple-Projekt um die Zeiten einzustellen.
In der Vis-2  Version 2.4.x hatte dies funktioniert, wobei mir bei der Zeit-Eingabe ein anderes Design angezeigt wurde.
Daher vermute ich, dass eine alte Version vom Widget hinterlegt ist. "Warum" ist mir nicht bekannt.

### To Reproduce

Use Gestylt jqui - Input Time
Datapoint auswählen (String mit unit: "hh:mm" )
Zeit auswählen

### Expected behavior

Eigendlich kenn ich das Widget mit "Schiebe-Reglern" zur Einstellung der Zeit

Datenpunkt wird mit String mit unit: "hh:mm" gespeichert

### Screenshots & Logfiles

iobroker.vis-2@2.6.1 using theme "colored"
Prompt.js:14 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:15 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:16 Help us to create open source project with reactJS!
Prompt.js:17 See you :)
socket.io.js:66 [2023-11-20T17:10:10.038Z] Try to connect
instrument.ts:145 Version vis-colorpicker: 2.0.3
instrument.ts:145 Version vis-jqui-mfd: 1.0.12
instrument.ts:145 Metro version: "1.2.0"
instrument.ts:145 Version trashschedule: 2.3.0
instrument.ts:145 Version Info-Adapter-Widget: 1.9.26
instrument.ts:145 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
instrument.ts:145 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
instrument.ts:145 Version vis-materialdesign: 0.5.94
instrument.ts:145 vis-materialdesign: vibration supported by device: 'true'
instrument.ts:145 vis-materialdesign: click audio file '/vis.0/materialdesign-widgets-click-sound.mp3' not exists!
(anonym) @ instrument.ts:145
instrument.ts:145 sentry initialized for vis-materialdesign
instrument.ts:145 Version vis-material-advanced: 1.7.3
:8082/vis-2/widgets/vis-2-widgets-gauges/customWidgets.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
instrument.ts:145 Cannot load i18n "vis2gaugeWidgets": Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: {}
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: {}
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: {}
(anonym) @ instrument.ts:145
instrument.ts:145 Translate: jqui_Input Time
instrument.ts:145 Translate: jqui_icon_increment
instrument.ts:145 Translate: jqui_Input Date
instrument.ts:145 Translate: colorpicker
instrument.ts:145 Translate: dwd
instrument.ts:145 Translate: echarts
instrument.ts:145 Translate: hqwidgets
instrument.ts:145 Translate: info
instrument.ts:145 Translate: jqplot
instrument.ts:145 Translate: jqui-mfd
instrument.ts:145 Translate: materialdesign
instrument.ts:145 Translate: metro
instrument.ts:145 Translate: swipe
instrument.ts:145 Translate: timeandweather
instrument.ts:145 Translate: trashschedule
instrument.ts:145 Translate: vis-inventwo
instrument.ts:145 Translate: vis-material-advanced
instrument.ts:145 Recalculate fields
instrument.ts:145 Translate: show code
instrument.ts:145 Translate: standard
instrument.ts:145 Translate: outlined
instrument.ts:145 Translate: filled
instrument.ts:145 Translate: 2 minutes
instrument.ts:145 Translate: 3 minutes
instrument.ts:145 Translate: 4 minutes
instrument.ts:145 Translate: 15 minutes
instrument.ts:145 Translate: 20 minutes
instrument.ts:145 Translate: 60 minutes
instrument.ts:145 Common user CSS not found: Not exists
(anonym) @ instrument.ts:145
instrument.ts:145 TypeError: e.minute is not a function
    at D.getMinutes (AdapterDayjs.js:503:20)
    at n (validateTime.js:46:47)
    at o (useValidation.js:10:27)
    at h (usePickerValue.js:191:3)
    at M (usePicker.js:21:31)
    at F (useDesktopPicker.js:61:7)
    at DesktopTimePicker.js:83:7
    at Cr (react-dom.production.min.js:167:247)
    at Vs (react-dom.production.min.js:193:57)
    at Cl (react-dom.production.min.js:294:275)
    at Hi (react-dom.production.min.js:280:389)
    at gi (react-dom.production.min.js:280:320)
    at fi (react-dom.production.min.js:280:180)
    at ri (react-dom.production.min.js:271:88)
    at oi (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:145
react-dom.production.min.js:283 Uncaught TypeError: e.minute is not a function
    at D.getMinutes (AdapterDayjs.js:503:20)
    at n (validateTime.js:46:47)
    at o (useValidation.js:10:27)
    at h (usePickerValue.js:191:3)
    at M (usePicker.js:21:31)
    at F (useDesktopPicker.js:61:7)
    at DesktopTimePicker.js:83:7
    at Cr (react-dom.production.min.js:167:247)
    at Vs (react-dom.production.min.js:193:57)
    at Cl (react-dom.production.min.js:294:275)
    at Hi (react-dom.production.min.js:280:389)
    at gi (react-dom.production.min.js:280:320)
    at fi (react-dom.production.min.js:280:180)
    at ri (react-dom.production.min.js:271:88)
    at oi (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
instrument.ts:145 [waitForWidgets] stop waiting for vis widgets after 500 retries
(anonym) @ instrument.ts:145

### Adapter version

2.6.1

### js-controller version

5.0.16

### Node version

18.17.0 

### Operating system

Rapsberry Pi 4, bullseye

### Additional context

_No response_

### LINKED ISSUE #387: Vis-2 widget "gestylt Zeiteingabe"
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ich möchte über das Zeiteingabe Widget die Steuerung für HeatingControl übernehmen. Wird aber eine Zeit ausgewählt (hier 05:00), wird in den zugehörigen Datenpunkt folgendes geschrieben: 
2024-02-27T04:00:00.000Z
Danach stürzt vis-2 ab und zeigt nur noch einen weißen Bildschirm, bis man den Datenpunkt wieder auf "05:00" setzt.
Auch bei anderen Adaptern, die das Format HH:MM benötigen passiert das gleiche.

### To Reproduce

1. Vis-2 gestylt Zeiteingabe widget erstellen und mit einem Datenpunkt im Format HH:MM verlinken.
2. In der Visualisierung eine Zeit auswählen

### Expected behavior

Im Datenpunkt sollte die Zeit als HH:MM stehen.

### Screenshots & Logfiles

Die Javascript-Konsole in Safari zeigt folgendes:

TypeError: e.minute is not a function. (In 'e.minute()', 'e.minute' is undefined)
(anonyme Funktion) — AdapterDayjs.js:503
g — validateTime.js:46
o — useValidation.js:10
h — usePickerValue.js:191
M — usePicker.js:21
F — useDesktopPicker.js:62
(anonyme Funktion) — DesktopTimePicker.js:83
yr — react-dom.production.min.js:167:249
Vs — react-dom.production.min.js:193
xl — react-dom.production.min.js:280:392
zl — react-dom.production.min.js:280:323
gl — react-dom.production.min.js:280:180
rl — react-dom.production.min.js:271:91
ol — react-dom.production.min.js:268:432
V — scheduler.production.min.js:13:205
j — scheduler.production.min.js:14:128

### Page or affected widget

_No response_

### Adapter version

2.9.34

### js-controller version

5.0.19

### Node version

18.17.1

### Operating system

Ubuntu 23.10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by foxriver76**
…ou want old behavior use checkbox 'asDate'

- closes #387, closes #183

### CODE REVIEW

**Comment by JoeSchwettmann** [comment]
I still have the problem, that I can not link a time or date picker to a datapoint. When I do this, I get a white screen.
Admin:6.13.16 VIS 2:2.9.32

**Comment by JoeSchwettmann** [comment]
Ok, I found, that I have the old version installed. I will try in next time to install the newest version from github.

**Comment by JoeSchwettmann** [comment]
Super! The newest version is fine for me.

**Comment by Leo-wq** [comment]
I still have the same Issue with version 1.1.1 and vis-2 version 2.9.32. Also for me there is no Checkbox 'asDate' .

**Comment by Leo-wq** [comment]
I updated vis2 manually to 2.9.64 and now it works. So it was vis and not the widget.

**Pull request merged**
